server:
  port: 80
  host:
    front: auction-seats.com

spring:
  config:
    activate:
      on-profile: prod  # 'prod' 프로파일이 활성화될 때 이 설정이 사용됩니다.
  data:
    redis:
      cluster:
        nodes:
          - localhost:6379
          - localhost:6380
          - localhost:6381
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/auction_seats
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret:
    key: ${jwt_secret_key}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3_bucket_name}
    region:
      static: ap-northeast-2
    stack:
      auto: false

payment:
  toss:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${SUCCESS_URL}
    fail-url: ${FAIL_URL}